/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fcubmvqejhlungggklfl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjdWJtdnFlamhsdW5nZ2drbGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzMDI1ODgsImV4cCI6MjA5MTg3ODU4OH0.dEUEUKUaCLBvui-aqHhJESOLlpaYH2utZbX50-47G6Y"